"use client";

import {
  CalendarDays,
  FileText,
  Loader2,
  Plus,
  Pencil,
  X,
} from "lucide-react";

import { useEffect, useMemo, useState } from "react";

import type {
  CreateInvoicePayload,
  Invoice,
  UpdateInvoicePayload,
} from "@/features/invoices/types/invoice.types";

interface InvoiceQuotationOption {
  id: string;
  quotationNumber: string;
  totalAmount: string | number;
  issueDate: string;
  expiryDate: string | null;
  client?: {
    id: string;
    companyName: string;
  };
  project?: {
    id: string;
    name: string;
  } | null;
  status:
    | "DRAFT"
    | "SENT"
    | "ACCEPTED"
    | "REJECTED"
    | "EXPIRED";

  invoice?: {
    id: string;
    invoiceNumber: string;
  } | null;
}

interface InvoiceFormModalProps {
  open: boolean;

  invoice?: Invoice | null;

  /**
   * Only accepted quotations should be passed here.
   */
  quotations: InvoiceQuotationOption[];

  /**
   * Generated by the page from the current invoice records.
   * Example: INV-1000, INV-1001, ...
   */
  nextInvoiceNumber: string;

  isSubmitting?: boolean;

  error?: string | null;

  onClose: () => void;

  onCreate: (
    data: CreateInvoicePayload,
  ) => void | Promise<void>;

  onUpdate: (
    data: UpdateInvoicePayload,
  ) => void | Promise<void>;
}

interface FormState {
  quotationId: string;
  invoiceNumber: string;
  issueDate: string;
  dueDate: string;
  notes: string;
}

interface FormErrors {
  quotationId?: string;
  issueDate?: string;
  dueDate?: string;
  notes?: string;
}

const emptyForm: FormState = {
  quotationId: "",
  invoiceNumber: "",
  issueDate: "",
  dueDate: "",
  notes: "",
};

export default function InvoiceFormModal({
  open,
  invoice,
  quotations,
  nextInvoiceNumber,
  isSubmitting = false,
  error,
  onClose,
  onCreate,
  onUpdate,
}: InvoiceFormModalProps) {
  const isEdit = Boolean(invoice);

  const [form, setForm] =
    useState<FormState>(emptyForm);

  const [errors, setErrors] =
    useState<FormErrors>({});

  /* ------------------------------------------------------------------------ */
  /* Initialize form                                                          */
  /* ------------------------------------------------------------------------ */

  useEffect(() => {
    if (!open) {
      return;
    }

    if (invoice) {
      setForm({
        quotationId: invoice.quotationId,

        invoiceNumber:
          invoice.invoiceNumber,

        issueDate:
          toDateInputValue(
            invoice.issueDate,
          ),

        dueDate:
          toDateInputValue(
            invoice.dueDate,
          ),

        notes:
          invoice.notes ?? "",
      });
    } else {
      setForm({
        quotationId: "",
        invoiceNumber:
          nextInvoiceNumber,
        issueDate:
          getTodayInputValue(),
        dueDate:
          getDefaultDueDate(),
        notes: "",
      });
    }

    setErrors({});
  }, [
    open,
    invoice,
    nextInvoiceNumber,
  ]);

  /* ------------------------------------------------------------------------ */
  /* Selected quotation                                                       */
  /* ------------------------------------------------------------------------ */

  const selectedQuotation =
    useMemo(
      () =>
        quotations.find(
          (quotation) =>
            quotation.id ===
            form.quotationId,
        ) ?? null,
      [
        form.quotationId,
        quotations,
      ],
    );

  /* ------------------------------------------------------------------------ */
  /* Closed                                                                   */
  /* ------------------------------------------------------------------------ */

  if (!open) {
    return null;
  }

  /* ------------------------------------------------------------------------ */
  /* Helpers                                                                  */
  /* ------------------------------------------------------------------------ */

  const updateField = (
    field: keyof FormState,
    value: string,
  ) => {
    setForm(
      (previous) => ({
        ...previous,
        [field]: value,
      }),
    );

    setErrors(
      (previous) => ({
        ...previous,
        [field]:
          undefined,
      }),
    );
  };

  const validate =
    (): boolean => {
      const nextErrors: FormErrors =
        {};

      /* Quotation */

      if (!isEdit && !form.quotationId) {
        nextErrors.quotationId =
          "Please select an accepted quotation.";
      }

      /* Issue date */

      if (!form.issueDate) {
        nextErrors.issueDate =
          "Issue date is required.";
      } else {
        const issueDate =
          new Date(
            form.issueDate,
          );

        if (
          Number.isNaN(
            issueDate.getTime(),
          )
        ) {
          nextErrors.issueDate =
            "Please enter a valid issue date.";
        }
      }

      /* Due date */

      if (!form.dueDate) {
        nextErrors.dueDate =
          "Due date is required.";
      } else {
        const issueDate =
          new Date(
            form.issueDate,
          );

        const dueDate =
          new Date(
            form.dueDate,
          );

        if (
          Number.isNaN(
            dueDate.getTime(),
          )
        ) {
          nextErrors.dueDate =
            "Please enter a valid due date.";
        }

        if (
          !Number.isNaN(
            issueDate.getTime(),
          ) &&
          !Number.isNaN(
            dueDate.getTime(),
          ) &&
          dueDate < issueDate
        ) {
          nextErrors.dueDate =
            "Due date cannot be before the issue date.";
        }
      }

      /* Notes */

      if (
        form.notes.trim()
          .length > 5000
      ) {
        nextErrors.notes =
          "Notes cannot exceed 5000 characters.";
      }

      setErrors(
        nextErrors,
      );

      return (
        Object.keys(
          nextErrors,
        ).length === 0
      );
    };

  /* ------------------------------------------------------------------------ */
  /* Submit                                                                   */
  /* ------------------------------------------------------------------------ */

  const handleSubmit = async (
    event: React.FormEvent<HTMLFormElement>,
  ) => {
    event.preventDefault();

    if (!validate()) {
      return;
    }

    if (isEdit) {
      const payload: UpdateInvoicePayload = {
        dueDate:
          form.dueDate,

        notes:
          form.notes.trim() ||
          undefined,
      };

      await onUpdate(
        payload,
      );

      return;
    }

    if (!form.quotationId) {
      return;
    }

    const payload: CreateInvoicePayload =
      {
        quotationId:
          form.quotationId,

        invoiceNumber:
          form.invoiceNumber,

        issueDate:
          form.issueDate,

        dueDate:
          form.dueDate,

        notes:
          form.notes.trim() ||
          undefined,
      };

    await onCreate(
      payload,
    );
  };

  /* ------------------------------------------------------------------------ */
  /* Render                                                                   */
  /* ------------------------------------------------------------------------ */

  return (
    <div className="fixed inset-0 z-[100] flex items-start justify-center overflow-y-auto bg-slate-900/40 p-4 sm:p-6">
      <div className="my-4 flex w-full max-w-2xl flex-col overflow-hidden rounded-xl bg-white shadow-xl sm:my-8">
        {/* Header */}

        <div className="flex shrink-0 items-start justify-between border-b border-slate-200 px-6 py-5">
          <div>
            <h2 className="text-lg font-semibold text-slate-900">
              {isEdit
                ? "Edit Invoice"
                : "Create Invoice"}
            </h2>

            <p className="mt-1 text-sm text-slate-500">
              {isEdit
                ? "Update the invoice details."
                : "Generate an invoice from an accepted quotation."}
            </p>
          </div>

          <button
            type="button"
            onClick={
              onClose
            }
            disabled={
              isSubmitting
            }
            className="flex h-8 w-8 items-center justify-center rounded-lg text-slate-400 transition hover:bg-slate-100 hover:text-slate-600 disabled:cursor-not-allowed disabled:opacity-50"
            aria-label="Close modal"
          >
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Form */}

        <form
          onSubmit={
            handleSubmit
          }
          className="max-h-[calc(100vh-8rem)] overflow-y-auto p-6"
        >
          <div className="grid grid-cols-1 gap-5 sm:grid-cols-2">
            {/* Invoice Number */}

            <div className="sm:col-span-2">
              <label
                htmlFor="invoiceNumber"
                className="mb-1.5 block text-sm font-medium text-slate-700"
              >
                Invoice Number
              </label>

              <div className="relative">
                <FileText className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />

                <input
                  id="invoiceNumber"
                  type="text"
                  value={
                    form.invoiceNumber
                  }
                  readOnly
                  disabled={
                    isSubmitting
                  }
                  className="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 pl-9 text-sm font-medium text-slate-700 outline-none"
                />
              </div>

              <p className="mt-1 text-xs text-slate-400">
                Generated automatically by the system.
              </p>
            </div>

            {/* Accepted quotation */}

            <div className="sm:col-span-2">
              <label
                htmlFor="invoiceQuotation"
                className="mb-1.5 block text-sm font-medium text-slate-700"
              >
                Accepted Quotation
                <span className="ml-1 text-red-500">
                  *
                </span>
              </label>

              {isEdit ? (
                <div className="rounded-lg border border-slate-200 bg-slate-50 px-4 py-3">
                  <p className="text-sm font-semibold text-slate-900">
                    {
                      invoice?.quotation
                        ?.quotationNumber
                    }
                  </p>

                  <p className="mt-1 text-xs text-slate-500">
                    The quotation linked to an invoice cannot be changed.
                  </p>
                </div>
              ) : (
                <>
                  <select
                    id="invoiceQuotation"
                    value={
                      form.quotationId
                    }
                    onChange={(
                      event,
                    ) =>
                      updateField(
                        "quotationId",
                        event.target
                          .value,
                      )
                    }
                    disabled={
                      isSubmitting
                    }
                    className={inputClass(
                      errors.quotationId,
                    )}
                  >
                    <option value="">
                      Select accepted quotation
                    </option>

                    {quotations.map(
                      (
                        quotation,
                      ) => (
                        <option
                          key={
                            quotation.id
                          }
                          value={
                            quotation.id
                          }
                        >
                          {
                            quotation.quotationNumber
                          }{" "}
                          —{" "}
                          {quotation.client
                            ?.companyName ??
                            "Unknown client"}{" "}
                          —{" "}
                          {formatCurrency(
                            quotation.totalAmount,
                          )}
                        </option>
                      ),
                    )}
                  </select>

                  <FieldError
                    message={
                      errors.quotationId
                    }
                  />

                  {quotations.length ===
                    0 && (
                    <p className="mt-1 text-xs text-amber-600">
                      No accepted quotations are currently available for invoicing.
                    </p>
                  )}
                </>
              )}
            </div>

            {/* Selected quotation summary */}

            {selectedQuotation &&
              !isEdit && (
                <div className="sm:col-span-2 rounded-lg border border-slate-200 bg-slate-50 p-4">
                  <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
                    <SummaryField
                      label="Client"
                      value={
                        selectedQuotation
                          .client
                          ?.companyName ??
                        "No client"
                      }
                    />

                    <SummaryField
                      label="Project"
                      value={
                        selectedQuotation
                          .project
                          ?.name ??
                        "No project"
                      }
                    />

                    <SummaryField
                      label="Quotation Total"
                      value={formatCurrency(
                        selectedQuotation.totalAmount,
                      )}
                    />
                  </div>
                </div>
              )}

            {/* Issue Date */}

            <div>
              <label
                htmlFor="invoiceIssueDate"
                className="mb-1.5 block text-sm font-medium text-slate-700"
              >
                Issue Date
                <span className="ml-1 text-red-500">
                  *
                </span>
              </label>

              <div className="relative">
                <CalendarDays className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />

                <input
                  id="invoiceIssueDate"
                  type="date"
                  value={
                    form.issueDate
                  }
                  onChange={(
                    event,
                  ) =>
                    updateField(
                      "issueDate",
                      event.target
                        .value,
                    )
                  }
                  disabled={
                    isSubmitting ||
                    isEdit
                  }
                  className={`pl-9 ${inputClass(
                    errors.issueDate,
                  )}`}
                />
              </div>

              <FieldError
                message={
                  errors.issueDate
                }
              />
            </div>

            {/* Due Date */}

            <div>
              <label
                htmlFor="invoiceDueDate"
                className="mb-1.5 block text-sm font-medium text-slate-700"
              >
                Due Date
                <span className="ml-1 text-red-500">
                  *
                </span>
              </label>

              <div className="relative">
                <CalendarDays className="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" />

                <input
                  id="invoiceDueDate"
                  type="date"
                  value={
                    form.dueDate
                  }
                  min={
                    form.issueDate ||
                    undefined
                  }
                  onChange={(
                    event,
                  ) =>
                    updateField(
                      "dueDate",
                      event.target
                        .value,
                    )
                  }
                  disabled={
                    isSubmitting
                  }
                  className={`pl-9 ${inputClass(
                    errors.dueDate,
                  )}`}
                />
              </div>

              <FieldError
                message={
                  errors.dueDate
                }
              />
            </div>

            {/* Notes */}

            <div className="sm:col-span-2">
              <label
                htmlFor="invoiceNotes"
                className="mb-1.5 block text-sm font-medium text-slate-700"
              >
                Notes
                <span className="ml-1 font-normal text-slate-400">
                  (Optional)
                </span>
              </label>

              <textarea
                id="invoiceNotes"
                value={
                  form.notes
                }
                onChange={(
                  event,
                ) =>
                  updateField(
                    "notes",
                    event.target
                      .value,
                  )
                }
                rows={4}
                maxLength={5000}
                placeholder="Additional invoice notes..."
                disabled={
                  isSubmitting
                }
                className={`${inputClass(
                  errors.notes,
                )} resize-none`}
              />

              <div className="mt-1 flex justify-between gap-4">
                <FieldError
                  message={
                    errors.notes
                  }
                />

                <p className="text-xs text-slate-400">
                  {
                    form.notes
                      .length
                  }
                  /5000
                </p>
              </div>
            </div>
          </div>

          {/* Financial preview */}

          {selectedQuotation && (
            <div className="mt-5 rounded-lg border border-slate-200 bg-white p-4">
              <p className="text-xs font-medium uppercase tracking-wide text-slate-400">
                Invoice Financial Summary
              </p>

              <div className="mt-3 space-y-2">
                <SummaryRow
                  label="Subtotal"
                  value={formatCurrency(
                    selectedQuotation
                      .id
                      ? getQuotationSubtotal(
                          selectedQuotation,
                        )
                      : 0,
                  )}
                />

                <SummaryRow
                  label="Discount"
                  value={`- ${formatCurrency(
                    getQuotationDiscount(
                      selectedQuotation,
                    ),
                  )}`}
                />

                <SummaryRow
                  label="Tax"
                  value={formatCurrency(
                    getQuotationTax(
                      selectedQuotation,
                    ),
                  )}
                />

                <div className="border-t border-slate-200 pt-3">
                  <SummaryRow
                    label="Total"
                    value={formatCurrency(
                      selectedQuotation.totalAmount,
                    )}
                    strong
                  />
                </div>
              </div>
            </div>
          )}

          {/* Backend error */}

          {error && (
            <div className="mt-5 rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
              {error}
            </div>
          )}

          {/* Actions */}

          <div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end">
            <button
              type="button"
              onClick={
                onClose
              }
              disabled={
                isSubmitting
              }
              className="rounded-lg border border-slate-300 px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50"
            >
              Cancel
            </button>

            <button
              type="submit"
              disabled={
                isSubmitting ||
                (!isEdit &&
                  quotations.length ===
                    0)
              }
              className="flex items-center justify-center gap-2 rounded-lg bg-slate-900 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
            >
              {isSubmitting ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" />

                  {isEdit
                    ? "Saving..."
                    : "Creating..."}
                </>
              ) : (
                <>
                  {isEdit ? (
                    <Pencil className="h-4 w-4" />
                  ) : (
                    <Plus className="h-4 w-4" />
                  )}

                  {isEdit
                    ? "Save Changes"
                    : "Create Draft Invoice"}
                </>
              )}
            </button>
          </div>
        </form>
      </div>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Summary field                                                              */
/* -------------------------------------------------------------------------- */

function SummaryField({
  label,
  value,
}: {
  label: string;
  value: string;
}) {
  return (
    <div>
      <p className="text-xs font-medium uppercase tracking-wide text-slate-400">
        {label}
      </p>

      <p className="mt-1 truncate text-sm font-medium text-slate-800">
        {value}
      </p>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Summary row                                                                */
/* -------------------------------------------------------------------------- */

function SummaryRow({
  label,
  value,
  strong = false,
}: {
  label: string;
  value: string;
  strong?: boolean;
}) {
  return (
    <div className="flex items-center justify-between gap-4">
      <span
        className={
          strong
            ? "text-sm font-semibold text-slate-900"
            : "text-sm text-slate-500"
        }
      >
        {label}
      </span>

      <span
        className={
          strong
            ? "text-lg font-bold text-slate-900"
            : "text-sm font-medium text-slate-700"
        }
      >
        {value}
      </span>
    </div>
  );
}

/* -------------------------------------------------------------------------- */
/* Input                                                                       */
/* -------------------------------------------------------------------------- */

function inputClass(
  error?: string,
) {
  return `w-full rounded-lg border px-3 py-2.5 text-sm text-slate-900 outline-none transition ${
    error
      ? "border-red-400 focus:border-red-500 focus:ring-2 focus:ring-red-100"
      : "border-slate-300 focus:border-slate-500 focus:ring-2 focus:ring-slate-200"
  } disabled:cursor-not-allowed disabled:bg-slate-50 disabled:opacity-70`;
}

/* -------------------------------------------------------------------------- */
/* Error                                                                       */
/* -------------------------------------------------------------------------- */

function FieldError({
  message,
}: {
  message?: string;
}) {
  if (!message) {
    return null;
  }

  return (
    <p className="mt-1 text-xs text-red-600">
      {message}
    </p>
  );
}

/* -------------------------------------------------------------------------- */
/* Date helpers                                                                */
/* -------------------------------------------------------------------------- */

function toDateInputValue(
  value?: string | null,
) {
  if (!value) {
    return "";
  }

  const date =
    new Date(value);

  if (
    Number.isNaN(
      date.getTime(),
    )
  ) {
    return "";
  }

  return date
    .toISOString()
    .slice(0, 10);
}

function getTodayInputValue() {
  return new Date()
    .toISOString()
    .slice(0, 10);
}

function getDefaultDueDate() {
  const date =
    new Date();

  date.setDate(
    date.getDate() + 7,
  );

  return date
    .toISOString()
    .slice(0, 10);
}

/* -------------------------------------------------------------------------- */
/* Quotation financial helpers                                                 */
/* -------------------------------------------------------------------------- */

function getQuotationSubtotal(
  quotation: InvoiceQuotationOption,
) {
  /**
   * The list response may not expose subtotal in a lightweight quotation type.
   *
   * For the invoice creation flow, the authoritative total is still the
   * quotation total returned by the backend.
   */
  return Number(
    quotation.totalAmount,
  );
}

function getQuotationDiscount(
  _quotation: InvoiceQuotationOption,
) {
  return 0;
}

function getQuotationTax(
  _quotation: InvoiceQuotationOption,
) {
  return 0;
}

/* -------------------------------------------------------------------------- */
/* Currency                                                                    */
/* -------------------------------------------------------------------------- */

function formatCurrency(
  value: string | number,
) {
  const amount =
    Number(value);

  if (
    !Number.isFinite(
      amount,
    )
  ) {
    return "PKR 0.00";
  }

  return new Intl.NumberFormat(
    "en-PK",
    {
      style: "currency",
      currency: "PKR",
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    },
  ).format(amount);
}