import { Router } from "express";
import healthRoutes from "./health.routes";
import authRoutes from "../modules/auth/auth.routes";
import userRoutes from "../modules/users/user.routes";
import departmentRoutes from "../modules/departments/department.routes";
import companyRoutes from "../modules/company/company.routes";
import clientRoutes from "../modules/clients/client.routes";
import contactPersonRoutes from "../modules/contact-persons/contactPerson.routes";
import projectRoutes from "../modules/projects/project.routes";
import taskRoutes from "../modules/tasks/task.routes";
import meetingRoutes from "../modules/meetings/meeting.routes";
import meetingParticipantRoutes from "../modules/meetingParticipants/meetingParticipant.routes";
import quotationRoutes from "../modules/quotations/quotation.routes";
import quotationItemRoutes from "../modules/quotationItems/quotationItem.routes";
import invoiceRoutes from "../modules/invoices/invoice.routes";
import invoiceItemRoutes from "../modules/invoiceItems/invoiceItem.routes";
import paymentRoutes from "../modules/payments/payment.routes";
import notificationRoutes from "../modules/notifications/notification.routes";
import fileRoutes from "../modules/files/file.routes";
import auditLogRoutes from "../modules/auditLogs/auditLog.routes";

const router = Router();

router.use("/", healthRoutes);
router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/departments", departmentRoutes);
router.use("/company", companyRoutes);
router.use("/clients", clientRoutes);
router.use("/contact-persons", contactPersonRoutes);
router.use("/projects", projectRoutes);
router.use("/tasks", taskRoutes);
router.use("/meetings", meetingRoutes);
router.use("/meetings", meetingParticipantRoutes);
router.use("/quotations", quotationRoutes);
router.use("/", quotationItemRoutes);
router.use("/invoices", invoiceRoutes);
router.use("/", invoiceItemRoutes);
router.use("/payments", paymentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/files", fileRoutes);
router.use("/audit-logs", auditLogRoutes);

export default router;